### PR TITLE
ask search engines not to crawl build or dev docs

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @keertip

**Comment by keertip** [comment]
Looks good! Should we delete the old be docs on GCS to make this all work?

**Comment by sethladd** [comment]
Yes, let's delete the old build-number docs. Can you deploy this, once I merge it? Thanks!

(Still need to do the redirects. That's next)

**Comment by keertip** [comment]
Sure, will deploy this version.

**Comment by keertip** [comment]
@sethladd, deployed.

**Comment by sethladd** [comment]
thanks!

**Pull request merged**
