### PR TITLE
fix redirects for older dev/stable and be builds

### LINKED ISSUE #59: fix redirects for older versions of dev and stable

### PR DESCRIPTION
**Pull request by keertip**
closes #59
closes #58

### CODE REVIEW

**Comment by sethladd** [comment]
Is this staged at a new version in App Engine? Will be happy to test it.

**Comment by keertip** [comment]
Yes, at https://gcs-new-redirects-dot-dartlang-api.appspot.com

**Comment by keertip** [comment]
@sethladd , can you give it another try? Have fixed the issue and also checked some of the urls from the search results.

**Comment by keertip** [comment]
Have deployed this version. Please open issues with redirects do not work.

**Pull request merged**
